### ISSUE TITLE
Add Kovan Testnet support?

### ISSUE THREAD

**Issue by theogravity** [martinlsanchez/daiauctions#3]
I'm not well-versed with web3 code, but was wondering how difficult it would be to add Kovan support.

I'd be willing to try my hand at it and create a PR if you can provide some details.

**Comment by martinlsanchez** [comment]
Hi,
I don't think that would be so hard to do it really, but for sure it's gonna be tricky.

My recommendation is to do following the same structure as we add support for Chinese.

Just, create a "/kovan" and put all needed files as the "/zh". 
For sure it's not the cleanest way but -doing that- you don't have to worry about anything, you can replace all Maker contracts addresses with the ones of Kovan (https://changelog.makerdao.com/releases/kovan/1.0.3/contracts.json) point web3 to Kovan and be up and running.

You will have to fix a couple of issues testing it because I use firebase routing to handle request, but for sure you can deduce how to do it from here (https://github.com/martinlsanchez/daiauctions/blob/master/firebase.json).

I kind of busy this days, but you can send me any question about it and I will try to answer as soon as I can. :-)
